name: replace bare import specifiers
on:
  push:
    branches:
      - main
env:
  SOURCE_BRANCH: main
  NEW_BRANCH: url-imports
jobs:
  replace:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - name: checkout ${{ env.NEW_BRANCH }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.NEW_BRANCH }}
      - name: merge
        run: |
          git merge --strategy-option=theirs origin/$SOURCE_BRANCH
      - name: set up deno
        run: |
          brew install deno
      - name: replace bare import specifiers
        run: |
          deno run -A ./.github/workflows/replace-bare-import-specifiers.js
      - name: stage files
        run: |
          git add --all --update --sparse
      - name: commit
        run: |
          git commit -m "chore: 🚚 replace bare import specifiers"
      - name: push
        run: |
          git push
