name: replace bare import specifiers
on:
  push:
    branches:
      - main
jobs:
  replace:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - name: setup env
        run: |
          REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 1)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2)
          SOURCE_BRANCH=main
          NEW_BRANCH=url-imports
      - name: clone
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git
      - name: step in
        run: |
          cd $REPO_NAME
      - name: checkout url-imports
        run: |
          git checkout $NEW_BRANCH
      - name: merge
        run: |
          git merge --ff-only $(git commit-tree -m "chore: 🔀 Throw away branch $NEW_BRANCH" -p $NEW_BRANCH -p $SOURCE_BRANCH $SOURCE_BRANCH^{tree})
      - name: set up deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
      - name: replace bare import specifiers
        run: |
          deno run -A ./.github/workflows/replace-bare-import-specifiers.js
      - name: stage files
        run: |
          git add --all
      - name: commit
        run: |
          git commit -m "chore: 🚚 replace bare import specifiers"
      - name: push
        run: |
          git push
